groups:
  - ios_credentials:
      - APPLE_CERTIFICATES
      - APPLE_PROVISIONING_PROFILES
      - APPLE_KEYCHAIN_PASSWORD

workflows:
  ios-simulator:
    name: iOS Simulator (Appetize)
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get
          
      - name: Build for Simulator
        script: |
          flutter build ios --debug --simulator
          
      - name: Zip app for upload
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app

    artifacts:
      - build/ios/iphonesimulator/Runner.app.zip
      - build/ios/iphonesimulator/*.app
      - /tmp/xcodebuild_logs/*.log
